all:
  hosts:
    web01:
      ansible_host: 172.31.12.0
    web02:
      ansible_host: 172.31.4.219
    db01:
      ansible_host: 172.31.1.75

  children:
    webservers:
      hosts:
        web01:
        web02:
    dbservers:
      hosts:
        db01:
    servers:
      children:
        webservers:
        dbservers:
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: user1.pem
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ec2-user@44.203.238.9 -i user1.pem"'
 

