all:
  hosts:
    web01:
      ansible_host: 172.31.6.185
    web02:
      ansible_host: 172.31.2.215
    db01:
      ansible_host: 172.31.4.209

  children:
    webservers:
      hosts:
        web01:
        web02:
    dbservers:
      hosts:
        db01:
      vars:
        name: 'DB_VARIABLE'
    servers:
      children:
        webservers:
        dbservers:
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: user1.pem
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q ec2-user@34.201.56.59 -i user1.pem"'
 

